apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cnf-ericsson
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  annotations:
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: default
  source:
    directory:
      jsonnet: {}
    path: deploy/enabled
    repoURL: https://github.com/alosadagrande/argocd.git
    targetRevision: cnf-ericsson
  syncPolicy:
    automated:
      selfHeal: true
