apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cnf-sno-cnfdb1
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: default
  source:
    directory:
      jsonnet: {}
      recurse: true
    path: deploy/enabled
    repoURL: https://github.com/alosadagrande/argocd.git
    targetRevision: cnf-sno-cnfdb1
  syncPolicy:
    automated:
      selfHeal: true
