apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cnf-operators
  namespace: argocd
operation:
  initiatedBy:
    automated: true
  retry:
    limit: 5
  sync:
    revision: 2a04563360dc1062b43e7c3f52758915bc9d5429
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: default
  source:
    directory:
      jsonnet: {}
      recurse: true
    path: deploy/enabled
    repoURL: https://github.com/alosadagrande/argocd.git
    targetRevision: main
  syncPolicy:
    automated:
      selfHeal: true
