apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cnf-operators
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
operation:
  initiatedBy:
    automated: true
  retry:
    limit: 5
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: default
  source:
    directory:
      jsonnet: {}
      recurse: true
    path: deploy/enabled
    repoURL: https://github.com/alosadagrande/argocd.git
    targetRevision: main
  syncPolicy:
    automated:
      selfHeal: true
