apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: eric1-config
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  annotations:
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: default
  source:
    directory:
      jsonnet: {}
    path: deploy/sno/4.8/enabled
    repoURL: https://github.com/alosadagrande/argocd.git
    targetRevision: eric1 
  syncPolicy:
    automated:
      selfHeal: true
  ignoreDifferences:
  - kind: Secret
    name: v4-0-config-user-idp-0-file-data
    namespace: openshift-authentication
    jsonPointers:
    - /
