apiVersion: nmstate.io/v1beta1
kind: NodeNetworkConfigurationPolicy
metadata:
  name: bond0-eno3-eno4-dhcp
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  nodeSelector:
    node-role.kubernetes.io/standard: ""
  desiredState:
    routes:
      config:
      - destination: 192.168.123.0/24
        metric: 150
        next-hop-address: 192.168.254.1 
        next-hop-interface: ens1f1
        table-id: 254
    interfaces:
    - name: bond0
      mtu: 1500 
      type: bond
      state: up
      ipv4:
        address:
        - ip: 192.168.122.250
          prefix-length: 24
        enabled: true
      link-aggregation:
        mode: balance-rr
        options:
          miimon: '140'
        slaves:
        - eno3
        - eno4
