apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: openshift-nmstate-operator-subscription
  namespace: openshift-nmstate 
spec:
  channel: "4.7" 
  name: kubernetes-nmstate-operator
  source: redhat-operators 
  sourceNamespace: openshift-marketplace
