# TODO handle namespace with var
resources:
  - performance/01-pao-namespace.yaml
  - performance/02-pao-operatorgroup.yaml
  - performance/03-pao-subscription.yaml
  - sriov/01-sriov-namespace.yaml
  - sriov/02-sriov-operatorgroup.yaml
  - sriov/03-sriov-subscription.yaml
  - cnv/01-cnv-namespace.yaml
  - cnv/02-cnv-operatorgroup.yaml
  - cnv/03-cnv-subscription.yaml
  - cnv/04-cnv-operator.yaml
