---
apiVersion: v1
kind: Node
metadata:
  labels:
    node-role.kubernetes.io/ht: ""
  name: openshift-worker-0
---
apiVersion: v1
kind: Node
metadata:
  labels:
    node-role.kubernetes.io/standard: ""
  name: openshift-worker-1
---
apiVersion: v1
kind: Node
metadata:
  labels:
    node-role.kubernetes.io/standard: ""
  name: openshift-worker-2
---
