apiVersion: v1
items:
- apiVersion: k8s.cni.cncf.io/v1
  kind: NetworkAttachmentDefinition
  metadata:
    name: macvlan-tuning
    namespace: testdpdk
  spec:
      config: '{ "cniVersion":"0.4.0", "plugins": [{"name":"test", "type":"macvlan", "master": "ens5f1", "ipam":{"type":"static", "addresses": [{"address": "10.19.11.101/26"}]}}, {"type": "tuning", "name": "mytuning", "sysctl": { "net.ipv4.conf.net1.proxy_arp": "1" }}]
      }'
  status: {}
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
