apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-monitoring-config
  namespace: openshift-monitoring
data:
  config.yaml: |
    enableUserWorkload: true 
    prometheusK8s:
      externalLabels:
        clustername: sno.cnfdb1.ericsson.lab.bos.redhat.com

