apiVersion: v1
kind: Namespace
metadata:
  labels:
    kubernetes.io/metadata.name: openshift-sriov-network-operator
  annotations:
    workload.openshift.io/allowed: management
  name: openshift-sriov-network-operator
spec: {}
status: {}
