apiVersion: sriovnetwork.openshift.io/v1
kind: SriovNetworkNodePolicy
metadata:
  name: xxv710-1
  namespace: openshift-sriov-network-operator
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  deviceType: vfio-pci
  isRdma: false
  linkType: eth
  mtu: 1500
  nicSelector:
    pfNames: ["ens1f1"]
    rootDevices:
    - "0000:12:00.1"
    vendor: "8086"
    deviceID: "158b"
  nodeSelector:
    node-role.kubernetes.io/master: ""
  numVfs: 8
  priority: 10
  resourceName: xxv710_1
