apiVersion: performance.openshift.io/v1alpha1
kind: PerformanceProfile
metadata:
  name: sno-cnfdb1 
spec:
  cpu:
    isolated: "2-39,42-79"
    reserved: "0-1,40-41"
  hugepages:
    defaultHugepagesSize: 1G
    pages:
    - count: 8 
      size: 1G
      node: 0
    - count: 8
      size: 1G
      node: 1
  nodeSelector:
    node-role.kubernetes.io/master: ""
  numa:
    topologyPolicy: single-numa-node
  realTimeKernel:
    enabled: false
