apiVersion: v1
items:
- apiVersion: k8s.cni.cncf.io/v1
  kind: NetworkAttachmentDefinition
  metadata:
    annotations:
      k8s.v1.cni.cncf.io/resourceName: openshift.io/sriov_netdevice_ens1f1_intelnic
    name: sriov-network-netdevice-intel
    namespace: testdpdk
  spec:
      config: '{ "cniVersion":"0.4.0", "name":"test", "type":"sriov", "spoofChk":"off", "vlan":0,"vlanQoS":0,"ipam":{"type":"static", "addresses": [{"address": "10.19.11.100/26"}]}
      }'
  status: {}
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
