apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfigPool
metadata:
  name: ht
  namespace: openshift-machine-config-operator
  labels:
    machineconfiguration.openshift.io/role: ht
spec:
  paused: false
  machineConfigSelector:
    matchExpressions:
      - key: machineconfiguration.openshift.io/role
        operator: In
        values: [worker,ht]
  nodeSelector:
    matchLabels:
      node-role.kubernetes.io/ht: ""
