apiVersion: sriovnetwork.openshift.io/v1
kind: SriovNetworkNodePolicy
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  name: sriov-networknodepolicy-netdevice-intel-ens1f1
  namespace: openshift-sriov-network-operator
spec:
  deviceType: netdevice
  isRdma: false
  linkType: eth
  mtu: 1500
  nicSelector:
    pfNames: ["ens1f1#0-15"] 
    rootDevices:
    - "0000:12:00.1"
    vendor: "8086"
    deviceID: "158b"
  nodeSelector:
    node-role.kubernetes.io/master: ""
  numVfs: 16
  priority: 10
  resourceName: sriov_netdevice_ens1f1_intelnic
